#!/usr/bin/env julia

# Official generator of the Bolivia stage subproblems (`bolivia/*.mof.json`).
#
# The JuMP/MAIN workflow does not depend on HydroPowerModels.jl at training or
# evaluation time: `build_hydropowermodels` (load_hydropowermodels.jl) reads one
# serialized stage subproblem per stage and re-parameterizes it. Those serialized
# models are produced HERE, and only here, by building the case through
# HydroPowerModels and letting JuMP's MathOptFormat writer serialize the result.
#
# The pipeline is deliberately narrow:
#
#   1. verify the three frozen input hashes (`verify_inputs`) — refuse to export
#      from anything but the committed case bytes;
#   2. parse the case with `HydroPowerModels.parse_folder`;
#   3. apply the canonical 0.6 active AND reactive load factor at model
#      construction (`scale_main_loads!`) — `PowerModels.json` stays byte-exact;
#   4. pass `stage_hours` from `hydro.json` into `create_param`, so
#      HydroPowerModels' own `constraint_hydro_balance` builds the water balance
#      with K = 0.0036 * stage_hours = 0.6048;
#   5. serialize subproblem 1 with `JuMP.write_to_file`;
#   6. re-read each file and assert its structural invariants
#      (`verify_generated_model`), including that K;
#   7. rewrite `bolivia/case_manifest.json` from the generated bytes and mirror
#      the whole case, byte for byte, into DecisionRulesExa.jl.
#
# No JSON coefficient is edited, no constraint is post-processed, and no equation
# is recreated by hand. If HydroPowerModels does not itself build the expected
# model, the assertions in step 6 fail and nothing downstream is updated.
#
# Usage (from examples/HydroPowerModels, with the pinned SDDP environment that
# carries HydroPowerModels, PowerModels, Clarabel and MadNLP):
#
#   julia --project=sddp export_subproblem_mof.jl
#   julia --project=sddp export_subproblem_mof.jl --formulations=ACPPowerModel
#   julia --project=sddp export_subproblem_mof.jl --exa-root=/path/to/DecisionRulesExa.jl
#
# `--exa-root` additionally mirrors the frozen inputs, the three exports and the
# manifest into the other engine and asserts byte-identity.

using HydroPowerModels
using PowerModels
using JuMP
# The solver only populates the subproblem models during `simulate`; the
# MathOptFormat export serializes model STRUCTURE (variables, constraints,
# objective, names), which is solver independent. Clarabel handles the conic and
# DC formulations, MadNLP the nonconvex polar-AC one — the same two solvers the
# production SDDP baseline uses.
using Clarabel
using MadNLP

include(joinpath(@__DIR__, "generate_canonical_case_artifacts.jl"))
using .HydroCanonicalCase

const FORMULATION_TYPES = Dict(
    "ACPPowerModel" => ACPPowerModel,
    "SOCWRConicPowerModel" => SOCWRConicPowerModel,
    "DCPPowerModel" => DCPPowerModel,
)

"""
    option(prefix) -> Union{Nothing,String}

Value of the first `--key=value` command-line argument whose key matches
`prefix`, or `nothing` when the option was not given.
"""
function option(prefix)
    index = findfirst(value -> startswith(value, prefix), ARGS)
    return isnothing(index) ? nothing : split(ARGS[index], '='; limit = 2)[2]
end

"""
    parse_canonical_case(case_dir) -> (alldata, stage_hours)

Parse the frozen case for one export and apply the canonical demand convention.

Re-parsed per formulation on purpose. `hydro_thermal_operation` and `simulate`
mutate the parsed dictionaries (fixed inflow values, per-subproblem solver
attributes), so sharing one `alldata` across the three builds would make each
export depend on which formulations ran before it — the exports would stop being
a function of the case bytes alone. Parsing is cheap next to building the policy
graph.

`stage_hours` is read back out of the PARSED case rather than taken from a
constant, then required to be the frozen value: this is the single point at
which the weekly water balance enters the exported model.
"""
function parse_canonical_case(case_dir)
    alldata = HydroPowerModels.parse_folder(case_dir; stages = TOTAL_STAGES)
    scale_main_loads!(alldata)
    stage_hours = Int(alldata[1]["hydro"]["stage_hours"])
    stage_hours == STAGE_HOURS ||
        error("parsed stage_hours is $stage_hours, expected $STAGE_HOURS")
    0.0036 * stage_hours == HYDRO_CONVERSION_K ||
        error("0.0036 * $stage_hours != $HYDRO_CONVERSION_K")
    return alldata, stage_hours
end

"""
    export_formulation(case_dir, formulation_name) -> String

Build the case through HydroPowerModels under one power-flow formulation and
serialize its first stage subproblem to `case_dir/<formulation_name>.mof.json`.

Stage 1 is the representative subproblem: every stage shares its structure and
differs only in the inflow right-hand side, which `build_hydropowermodels` turns
into a parameter. HydroPowerModels leaves one unnamed slack variable in the
subproblem; it is deleted before writing, because the loader identifies
variables by name.

# Returns
- `String`: the path written.
"""
function export_formulation(case_dir, formulation_name)
    alldata, stage_hours = parse_canonical_case(case_dir)
    formulation = FORMULATION_TYPES[formulation_name]
    optimizer = formulation == ACPPowerModel ?
        (() -> MadNLP.Optimizer(; print_level = 0)) :
        (() -> Clarabel.Optimizer(; verbose = false))

    params = create_param(;
        stages = TOTAL_STAGES,
        stage_hours = stage_hours,
        model_constructor_grid = formulation,
        post_method = PowerModels.build_opf,
        optimizer = optimizer,
    )
    model = hydro_thermal_operation(alldata, params)

    # `hydro_thermal_operation` has already built the policy graph, so the
    # structure exists without solving. The short simulate call is retained only
    # because it populates solver attributes on the subproblems; a MadNLP failure
    # at a stressed default start does not invalidate the structure, so it is
    # tolerated rather than fatal.
    try
        HydroPowerModels.simulate(model, 2)
    catch err
        @warn "simulate() failed; exporting model structure regardless" formulation_name err
    end

    subproblem = model.forward_graph[1].subproblem
    unnamed = findfirst(v -> name(v) == "", all_variables(subproblem))
    isnothing(unnamed) || delete(subproblem, all_variables(subproblem)[unnamed])

    path = joinpath(case_dir, formulation_name * ".mof.json")
    JuMP.write_to_file(subproblem, path)
    return path
end

function main()
    case_dir = joinpath(@__DIR__, "bolivia")

    requested = option("--formulations=")
    formulations = isnothing(requested) ? collect(FORMULATIONS) :
        String.(split(requested, ','))
    for formulation_name in formulations
        haskey(FORMULATION_TYPES, formulation_name) ||
            error("unknown formulation $formulation_name")
    end

    counts = verify_inputs(case_dir)
    @info "Frozen case verified" case_dir counts
    @info "Canonical demand applied at construction" pd_scale = ACTIVE_LOAD_FACTOR qd_scale =
        REACTIVE_LOAD_FACTOR deficit_cost = ACTIVE_DEFICIT_COST
    @info "Water balance" stage_hours = STAGE_HOURS K = HYDRO_CONVERSION_K stages = TOTAL_STAGES

    for formulation_name in formulations
        path = export_formulation(case_dir, formulation_name)
        summary = verify_generated_model(path, formulation_name)
        @info "Exported and structurally validated" formulation_name path summary
    end

    # The manifest is derived from the bytes just written, then re-verified from
    # disk, so a manifest can never describe a model that was not exported.
    manifest = HydroCanonicalCase.build_manifest(case_dir)
    manifest_file = HydroCanonicalCase.write_manifest(case_dir, manifest)
    HydroCanonicalCase.verify(case_dir)

    mirrored = String[]
    exa_root = option("--exa-root=")
    if exa_root !== nothing
        mirrored = mirror_case!(
            case_dir,
            joinpath(exa_root, "examples", "HydroPowerModels", "bolivia"),
        )
    end

    for formulation_name in formulations
        println(
            formulation_name, ".mof.json sha256 ",
            sha256_file(joinpath(case_dir, formulation_name * ".mof.json")),
        )
    end
    println("case_manifest.json sha256 ", sha256_file(manifest_file))
    isempty(mirrored) || println("mirrored to $exa_root: ", join(mirrored, ", "))
end

(abspath(PROGRAM_FILE) == @__FILE__) && main()
